### ISSUE TITLE
Error "ValueError: Length mismatch: Expected axis has 1 elements, new values have 6 elements" during training

### ISSUE THREAD

**Issue by vicbp1** [AI-sandbox/XGMix#6]
Hi!
I am running XGMIX from the scratch for 8K individuals and  I am having problems during the run of an specific chr. I receive the following message:

/autofs/chib/F1_merged_data/imputed_above0.9/merging_process/XGMix/Utils/postprocess.py:62: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  meta_data = np.array([chm_array, spos, epos, sgpos, egpos, n_snps]).T
Traceback (most recent call last):
  File "/local/chib/F1_merged_data/imputed_above0.9/merging_process/XGMix/XGMIX.py", line 363, in <module>
    main(args, verbose=verbose, run_simulation=run_simulation, founders_ratios=founders_ratios,
  File "/local/chib/F1_merged_data/imputed_above0.9/merging_process/XGMix/XGMIX.py", line 302, in main
    meta_data = get_meta_data(args.chm, model.snp_pos,
  File "/autofs/chib/F1_merged_data/imputed_above0.9/merging_process/XGMix/Utils/postprocess.py", line 64, in get_meta_data
    meta_data_df.columns = ["chm", "spos", "epos", "sgpos", "egpos", "n snps"]
  File "/local/chib/toconnor_grp/victor/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/local/chib/victor/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/local/chib/victor/miniconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 177, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 6 elements

It seems that the training is running well and the problem occurs after the LA inferences since the programs stops when "Writing inference to disc". I tried new runs by creating new inputs and providing more memory, but with no success. Other chrs did not showed this problem. Can you help me please.

**Comment by weekend37** [comment]
Great finding. 
The writing module didn't anticipate the window size to be a divisor of the chromosome length in snps.
It has now been fixed.
Thanks Victor.
